spring:
  application:
    name: pokedex-at-home

springdoc:
  title: ${SPRINGDOC_TITLE:Pokédex At Home}
  version: ${SPRINGDOC_VERSION:v1}

webclient:
  pokeapi:
    base-url: ${POKEAPI_BASE_URL:https://pokeapi.co/api/v2}
  fun-translations:
    base-url: ${FUNTRANSLATIONS_BASE_URL:https://api.funtranslations.com/translate/}